// Generated by Haxe 4.3.1
var $hx_exports = typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this;
(function ($global) { "use strict";
$hx_exports["esb"] = $hx_exports["esb"] || {};
$hx_exports["esb"]["core"] = $hx_exports["esb"]["core"] || {};
$hx_exports["esb"]["core"]["config"] = $hx_exports["esb"]["core"]["config"] || {};
$hx_exports["esb"]["core"]["config"]["sections"] = $hx_exports["esb"]["core"]["config"]["sections"] || {};
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw haxe_Exception.thrown("EReg::matched");
		}
	}
	,matchedPos: function() {
		if(this.r.m == null) {
			throw haxe_Exception.thrown("No string matched");
		}
		return { pos : this.r.m.index, len : this.r.m[0].length};
	}
	,matchSub: function(s,pos,len) {
		if(len == null) {
			len = -1;
		}
		if(this.r.global) {
			this.r.lastIndex = pos;
			this.r.m = this.r.exec(len < 0 ? s : HxOverrides.substr(s,0,pos + len));
			var b = this.r.m != null;
			if(b) {
				this.r.s = s;
			}
			return b;
		} else {
			var b = this.match(len < 0 ? HxOverrides.substr(s,pos,null) : HxOverrides.substr(s,pos,len));
			if(b) {
				this.r.s = s;
				this.r.m.index += pos;
			}
			return b;
		}
	}
	,map: function(s,f) {
		var offset = 0;
		var buf_b = "";
		do {
			if(offset >= s.length) {
				break;
			} else if(!this.matchSub(s,offset)) {
				buf_b += Std.string(HxOverrides.substr(s,offset,null));
				break;
			}
			var p = this.matchedPos();
			buf_b += Std.string(HxOverrides.substr(s,offset,p.pos - offset));
			buf_b += Std.string(f(this));
			if(p.len == 0) {
				buf_b += Std.string(HxOverrides.substr(s,p.pos,1));
				offset = p.pos + 1;
			} else {
				offset = p.pos + p.len;
			}
		} while(this.r.global);
		if(!this.r.global && offset > 0 && offset < s.length) {
			buf_b += Std.string(HxOverrides.substr(s,offset,null));
		}
		return buf_b;
	}
	,__class__: EReg
};
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
var json2object_reader_BaseParser = function(errors,putils,errorType) {
	this.errors = errors;
	this.putils = putils;
	this.errorType = errorType;
};
json2object_reader_BaseParser.__name__ = true;
json2object_reader_BaseParser.prototype = {
	fromJson: function(jsonString,filename) {
		if(filename == null) {
			filename = "";
		}
		this.putils = new json2object_PositionUtils(jsonString);
		this.errors = [];
		try {
			var json = new hxjsonast_Parser(jsonString,filename).doParse();
			this.loadJson(json);
		} catch( _g ) {
			var _g1 = haxe_Exception.caught(_g).unwrap();
			if(((_g1) instanceof hxjsonast_Error)) {
				var e = _g1;
				this.errors.push(json2object_Error.ParserError(e.message,this.putils.convertPosition(e.pos)));
			} else {
				throw _g;
			}
		}
		return this.value;
	}
	,loadJson: function(json,variable) {
		if(variable == null) {
			variable = "";
		}
		var pos = this.putils.convertPosition(json.pos);
		var _g = json.value;
		switch(_g._hx_index) {
		case 0:
			var s = _g.s;
			this.loadJsonString(s,pos,variable);
			break;
		case 1:
			var n = _g.s;
			this.loadJsonNumber(n,pos,variable);
			break;
		case 2:
			var o = _g.fields;
			this.loadJsonObject(o,pos,variable);
			break;
		case 3:
			var a = _g.values;
			this.loadJsonArray(a,pos,variable);
			break;
		case 4:
			var b = _g.b;
			this.loadJsonBool(b,pos,variable);
			break;
		case 5:
			this.loadJsonNull(pos,variable);
			break;
		}
		return this.value;
	}
	,loadJsonNull: function(pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonString: function(s,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonNumber: function(f,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonBool: function(b,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonArray: function(a,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonObject: function(o,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadObjectField: function(loadJsonFn,field,name,assigned,defaultValue,pos) {
		try {
			var ret = loadJsonFn(field.value,field.name);
			this.mapSet(assigned,name,true);
			return ret;
		} catch( _g ) {
			var _g1 = haxe_Exception.caught(_g).unwrap();
			if(js_Boot.__instanceof(_g1,json2object_InternalError)) {
				var e = _g1;
				if(e != json2object_InternalError.ParsingThrow) {
					throw haxe_Exception.thrown(e);
				}
			} else {
				var e = _g1;
				this.errors.push(json2object_Error.CustomFunctionException(e,pos));
			}
		}
		return defaultValue;
	}
	,objectSetupAssign: function(assigned,keys,values) {
		var _g = 0;
		var _g1 = keys.length;
		while(_g < _g1) {
			var i = _g++;
			this.mapSet(assigned,keys[i],values[i]);
		}
	}
	,objectErrors: function(assigned,pos) {
		var lastPos = this.putils.convertPosition(new hxjsonast_Position(pos.file,pos.max - 1,pos.max - 1));
		var h = assigned.h;
		var s_h = h;
		var s_keys = Object.keys(h);
		var s_length = s_keys.length;
		var s_current = 0;
		while(s_current < s_length) {
			var s = s_keys[s_current++];
			if(!assigned.h[s]) {
				this.errors.push(json2object_Error.UninitializedVariable(s,lastPos));
			}
		}
	}
	,onIncorrectType: function(pos,variable) {
		this.parsingThrow();
	}
	,parsingThrow: function() {
		if(this.errorType != 0) {
			throw haxe_Exception.thrown(json2object_InternalError.ParsingThrow);
		}
	}
	,mapSet: function(map,key,value) {
		map.h[key] = value;
	}
	,__class__: json2object_reader_BaseParser
};
var JsonParser_$0 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$0.__name__ = true;
JsonParser_$0.__super__ = json2object_reader_BaseParser;
JsonParser_$0.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.EsbConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["bundles","queues","_properties"],[false,false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "bundles":
				this.value.bundles = this.loadObjectField(($_=new JsonParser_$2(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"bundles",assigned,this.value.bundles,pos);
				break;
			case "properties":
				this.value._properties = this.loadObjectField(($_=new JsonParser_$6(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"_properties",assigned,this.value._properties,pos);
				break;
			case "queues":
				this.value.queues = this.loadObjectField(($_=new JsonParser_$4(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"queues",assigned,this.value.queues,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_EsbConfig.prototype);
		value.bundles = new JsonParser_$2([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.queues = new JsonParser_$4([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value._properties = new JsonParser_$6([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$0
});
var JsonParser_$10 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$10.__name__ = true;
JsonParser_$10.__super__ = json2object_reader_BaseParser;
JsonParser_$10.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.QueueConsumerConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["className","_properties"],[false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "class":
				this.value.className = this.loadObjectField(($_=new JsonParser_$7(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"className",assigned,this.value.className,pos);
				break;
			case "properties":
				this.value._properties = this.loadObjectField(($_=new JsonParser_$6(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"_properties",assigned,this.value._properties,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_QueueConsumerConfig.prototype);
		value.className = new JsonParser_$7([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value._properties = new JsonParser_$6([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$10
});
var JsonParser_$11 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$11.__name__ = true;
JsonParser_$11.__super__ = json2object_reader_BaseParser;
JsonParser_$11.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.QueueProducerConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["className","_properties"],[false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "class":
				this.value.className = this.loadObjectField(($_=new JsonParser_$7(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"className",assigned,this.value.className,pos);
				break;
			case "properties":
				this.value._properties = this.loadObjectField(($_=new JsonParser_$6(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"_properties",assigned,this.value._properties,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_QueueProducerConfig.prototype);
		value.className = new JsonParser_$7([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value._properties = new JsonParser_$6([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$11
});
var JsonParser_$12 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$12.__name__ = true;
JsonParser_$12.__super__ = json2object_reader_BaseParser;
JsonParser_$12.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.BundleConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["name","bundleFile","prefixes","_properties"],[false,false,true,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "bundle-file":
				this.value.bundleFile = this.loadObjectField(($_=new JsonParser_$7(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"bundleFile",assigned,this.value.bundleFile,pos);
				break;
			case "name":
				this.value.name = this.loadObjectField(($_=new JsonParser_$7(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"name",assigned,this.value.name,pos);
				break;
			case "prefixes":
				this.value.prefixes = this.loadObjectField(($_=new JsonParser_$14(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"prefixes",assigned,this.value.prefixes,pos);
				break;
			case "properties":
				this.value._properties = this.loadObjectField(($_=new JsonParser_$6(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"_properties",assigned,this.value._properties,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_BundleConfig.prototype);
		value.name = new JsonParser_$7([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.bundleFile = new JsonParser_$7([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.prefixes = new haxe_ds_StringMap();
		value._properties = new JsonParser_$6([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$12
});
var JsonParser_$14 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$14.__name__ = true;
JsonParser_$14.__super__ = json2object_reader_BaseParser;
JsonParser_$14.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"haxe.ds.Map<String, esb.core.config.sections.BundlePrefixConfig>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		this.value = new haxe_ds_StringMap();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			var this1 = this.value;
			var key;
			try {
				var key1 = new JsonParser_$7(this.errors,this.putils,2);
				var _this = this.putils;
				key = key1.loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JString(field.name),new hxjsonast_Position(pos.file,pos.min - 1,pos.max - 1)),variable);
			} catch( _g1 ) {
				var _g2 = haxe_Exception.caught(_g1).unwrap();
				if(js_Boot.__instanceof(_g2,json2object_InternalError)) {
					var e = _g2;
					if(e != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e);
					}
					continue;
				} else {
					throw _g1;
				}
			}
			var value;
			try {
				value = new JsonParser_$15(this.errors,this.putils,2).loadJson(field.value,field.name);
			} catch( _g3 ) {
				var _g4 = haxe_Exception.caught(_g3).unwrap();
				if(js_Boot.__instanceof(_g4,json2object_InternalError)) {
					var e1 = _g4;
					if(e1 != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e1);
					}
					continue;
				} else {
					throw _g3;
				}
			}
			this1.h[key] = value;
		}
	}
	,__class__: JsonParser_$14
});
var JsonParser_$15 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$15.__name__ = true;
JsonParser_$15.__super__ = json2object_reader_BaseParser;
JsonParser_$15.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.BundlePrefixConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["consumer","producer"],[false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "consumer":
				this.value.consumer = this.loadObjectField(($_=new JsonParser_$16(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"consumer",assigned,this.value.consumer,pos);
				break;
			case "producer":
				this.value.producer = this.loadObjectField(($_=new JsonParser_$17(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"producer",assigned,this.value.producer,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_BundlePrefixConfig.prototype);
		value.consumer = new JsonParser_$16([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.producer = new JsonParser_$17([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$15
});
var JsonParser_$16 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$16.__name__ = true;
JsonParser_$16.__super__ = json2object_reader_BaseParser;
JsonParser_$16.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.BundlePrefixConsumerConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["className","internal","bundle"],[false,false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "bundle":
				var v = this.loadObjectField(($_=new JsonParser_$12(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"bundle",assigned,this.value.get_bundle(),pos);
				if(v != null) {
					this.value.bundle = v;
				}
				break;
			case "class":
				this.value.className = this.loadObjectField(($_=new JsonParser_$7(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"className",assigned,this.value.className,pos);
				break;
			case "internal":
				this.value.internal = this.loadObjectField(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"internal",assigned,this.value.internal,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_BundlePrefixConsumerConfig.prototype);
		value.className = new JsonParser_$7([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.internal = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.bundle = new JsonParser_$12([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$16
});
var JsonParser_$17 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$17.__name__ = true;
JsonParser_$17.__super__ = json2object_reader_BaseParser;
JsonParser_$17.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.BundlePrefixProducerConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["className","internal","bundle"],[false,false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "bundle":
				var v = this.loadObjectField(($_=new JsonParser_$12(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"bundle",assigned,this.value.get_bundle(),pos);
				if(v != null) {
					this.value.bundle = v;
				}
				break;
			case "class":
				this.value.className = this.loadObjectField(($_=new JsonParser_$7(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"className",assigned,this.value.className,pos);
				break;
			case "internal":
				this.value.internal = this.loadObjectField(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"internal",assigned,this.value.internal,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_BundlePrefixProducerConfig.prototype);
		value.className = new JsonParser_$7([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.internal = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.bundle = new JsonParser_$12([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$17
});
var JsonParser_$2 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$2.__name__ = true;
JsonParser_$2.__super__ = json2object_reader_BaseParser;
JsonParser_$2.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"haxe.ds.Map<String, esb.core.config.sections.BundleConfig>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		this.value = new haxe_ds_StringMap();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			var this1 = this.value;
			var key;
			try {
				var key1 = new JsonParser_$7(this.errors,this.putils,2);
				var _this = this.putils;
				key = key1.loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JString(field.name),new hxjsonast_Position(pos.file,pos.min - 1,pos.max - 1)),variable);
			} catch( _g1 ) {
				var _g2 = haxe_Exception.caught(_g1).unwrap();
				if(js_Boot.__instanceof(_g2,json2object_InternalError)) {
					var e = _g2;
					if(e != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e);
					}
					continue;
				} else {
					throw _g1;
				}
			}
			var value;
			try {
				value = new JsonParser_$12(this.errors,this.putils,2).loadJson(field.value,field.name);
			} catch( _g3 ) {
				var _g4 = haxe_Exception.caught(_g3).unwrap();
				if(js_Boot.__instanceof(_g4,json2object_InternalError)) {
					var e1 = _g4;
					if(e1 != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e1);
					}
					continue;
				} else {
					throw _g3;
				}
			}
			this1.h[key] = value;
		}
	}
	,__class__: JsonParser_$2
});
var JsonParser_$4 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$4.__name__ = true;
JsonParser_$4.__super__ = json2object_reader_BaseParser;
JsonParser_$4.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"haxe.ds.Map<String, esb.core.config.sections.QueueConfig>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		this.value = new haxe_ds_StringMap();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			var this1 = this.value;
			var key;
			try {
				var key1 = new JsonParser_$7(this.errors,this.putils,2);
				var _this = this.putils;
				key = key1.loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JString(field.name),new hxjsonast_Position(pos.file,pos.min - 1,pos.max - 1)),variable);
			} catch( _g1 ) {
				var _g2 = haxe_Exception.caught(_g1).unwrap();
				if(js_Boot.__instanceof(_g2,json2object_InternalError)) {
					var e = _g2;
					if(e != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e);
					}
					continue;
				} else {
					throw _g1;
				}
			}
			var value;
			try {
				value = new JsonParser_$8(this.errors,this.putils,2).loadJson(field.value,field.name);
			} catch( _g3 ) {
				var _g4 = haxe_Exception.caught(_g3).unwrap();
				if(js_Boot.__instanceof(_g4,json2object_InternalError)) {
					var e1 = _g4;
					if(e1 != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e1);
					}
					continue;
				} else {
					throw _g3;
				}
			}
			this1.h[key] = value;
		}
	}
	,__class__: JsonParser_$4
});
var JsonParser_$6 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$6.__name__ = true;
JsonParser_$6.__super__ = json2object_reader_BaseParser;
JsonParser_$6.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"haxe.ds.Map<String, String>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		this.value = new haxe_ds_StringMap();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			var this1 = this.value;
			var key;
			try {
				var key1 = new JsonParser_$7(this.errors,this.putils,2);
				var _this = this.putils;
				key = key1.loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JString(field.name),new hxjsonast_Position(pos.file,pos.min - 1,pos.max - 1)),variable);
			} catch( _g1 ) {
				var _g2 = haxe_Exception.caught(_g1).unwrap();
				if(js_Boot.__instanceof(_g2,json2object_InternalError)) {
					var e = _g2;
					if(e != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e);
					}
					continue;
				} else {
					throw _g1;
				}
			}
			var value;
			try {
				value = new JsonParser_$7(this.errors,this.putils,2).loadJson(field.value,field.name);
			} catch( _g3 ) {
				var _g4 = haxe_Exception.caught(_g3).unwrap();
				if(js_Boot.__instanceof(_g4,json2object_InternalError)) {
					var e1 = _g4;
					if(e1 != json2object_InternalError.ParsingThrow) {
						throw haxe_Exception.thrown(e1);
					}
					continue;
				} else {
					throw _g3;
				}
			}
			this1.h[key] = value;
		}
	}
	,__class__: JsonParser_$6
});
var JsonParser_$7 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$7.__name__ = true;
JsonParser_$7.__super__ = json2object_reader_BaseParser;
JsonParser_$7.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"String",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonString: function(s,pos,variable) {
		this.value = s;
	}
	,__class__: JsonParser_$7
});
var JsonParser_$8 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$8.__name__ = true;
JsonParser_$8.__super__ = json2object_reader_BaseParser;
JsonParser_$8.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"esb.core.config.sections.QueueConfig",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["isDefault","consumer","producer","_properties"],[false,false,false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "consumer":
				this.value.consumer = this.loadObjectField(($_=new JsonParser_$10(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"consumer",assigned,this.value.consumer,pos);
				break;
			case "default":
				this.value.isDefault = this.loadObjectField(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"isDefault",assigned,this.value.isDefault,pos);
				break;
			case "producer":
				this.value.producer = this.loadObjectField(($_=new JsonParser_$11(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"producer",assigned,this.value.producer,pos);
				break;
			case "properties":
				this.value._properties = this.loadObjectField(($_=new JsonParser_$6(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"_properties",assigned,this.value._properties,pos);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var value = Object.create(esb_core_config_sections_QueueConfig.prototype);
		value.isDefault = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.consumer = new JsonParser_$10([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value.producer = new JsonParser_$11([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		value._properties = new JsonParser_$6([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return value;
	}
	,__class__: JsonParser_$8
});
var JsonParser_$9 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
	this.value = false;
};
JsonParser_$9.__name__ = true;
JsonParser_$9.__super__ = json2object_reader_BaseParser;
JsonParser_$9.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"Bool",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonBool: function(b,pos,variable) {
		this.value = b;
	}
	,__class__: JsonParser_$9
});
Math.__name__ = true;
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( _g ) {
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) {
			a.push(f);
		}
		}
	}
	return a;
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringBuf = function() {
	this.b = "";
};
StringBuf.__name__ = true;
StringBuf.prototype = {
	__class__: StringBuf
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.startsWith = function(s,start) {
	if(s.length >= start.length) {
		return s.lastIndexOf(start,0) == 0;
	} else {
		return false;
	}
};
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
var Test = function() { };
Test.__name__ = true;
Test.main = function() {
	var c = esb_core_config_ConfigParser.fromFile("example.json");
	var h = c.bundles.h;
	var bundleName_h = h;
	var bundleName_keys = Object.keys(h);
	var bundleName_length = bundleName_keys.length;
	var bundleName_current = 0;
	while(bundleName_current < bundleName_length) {
		var bundleName = bundleName_keys[bundleName_current++];
		haxe_Log.trace(bundleName,{ fileName : "Test.hx", lineNumber : 10, className : "Test", methodName : "main"});
		var bundle = c.bundles.h[bundleName];
		var h = bundle.prefixes.h;
		var prefixName_h = h;
		var prefixName_keys = Object.keys(h);
		var prefixName_length = prefixName_keys.length;
		var prefixName_current = 0;
		while(prefixName_current < prefixName_length) {
			var prefixName = prefixName_keys[prefixName_current++];
			haxe_Log.trace("    " + prefixName,{ fileName : "Test.hx", lineNumber : 13, className : "Test", methodName : "main", customParams : [bundle.name]});
			haxe_Log.trace("    " + bundle.prefixes.h[prefixName].consumer.className,{ fileName : "Test.hx", lineNumber : 14, className : "Test", methodName : "main"});
			haxe_Log.trace("    " + bundle.prefixes.h[prefixName].producer.className,{ fileName : "Test.hx", lineNumber : 15, className : "Test", methodName : "main"});
		}
	}
	haxe_Log.trace(c.findPrefix("http",true).get_bundle().bundleFile,{ fileName : "Test.hx", lineNumber : 19, className : "Test", methodName : "main"});
	var propName = c.findPrefix("file",false).get_bundle().properties.keys();
	while(propName.hasNext()) {
		var propName1 = propName.next();
		haxe_Log.trace(propName1 + " = " + c.findPrefix("file",false).get_bundle().properties.get(propName1),{ fileName : "Test.hx", lineNumber : 22, className : "Test", methodName : "main"});
	}
	var propName = c.properties.keys();
	while(propName.hasNext()) {
		var propName1 = propName.next();
		haxe_Log.trace(propName1 + " = " + c.properties.get(propName1),{ fileName : "Test.hx", lineNumber : 25, className : "Test", methodName : "main"});
	}
	var h = c.queues.h;
	var queueType_h = h;
	var queueType_keys = Object.keys(h);
	var queueType_length = queueType_keys.length;
	var queueType_current = 0;
	while(queueType_current < queueType_length) {
		var queueType = queueType_keys[queueType_current++];
		var queueConfig = c.queues.h[queueType];
		haxe_Log.trace(queueType,{ fileName : "Test.hx", lineNumber : 30, className : "Test", methodName : "main", customParams : [queueConfig.isDefault]});
		haxe_Log.trace(queueConfig.consumer.className,{ fileName : "Test.hx", lineNumber : 31, className : "Test", methodName : "main"});
		haxe_Log.trace(queueConfig.consumer.properties.get("queueName"),{ fileName : "Test.hx", lineNumber : 32, className : "Test", methodName : "main"});
		haxe_Log.trace(queueConfig.producer.className,{ fileName : "Test.hx", lineNumber : 33, className : "Test", methodName : "main"});
		var queueConfig1 = queueConfig.producer.properties;
		var _g = new haxe_ds_StringMap();
		_g.h["endpoint"] = "bob";
		haxe_Log.trace(queueConfig1.get("queueName",null,_g),{ fileName : "Test.hx", lineNumber : 34, className : "Test", methodName : "main"});
		haxe_Log.trace(queueConfig.producer.properties.get("brokerUrl"),{ fileName : "Test.hx", lineNumber : 35, className : "Test", methodName : "main"});
	}
};
var ValueType = $hxEnums["ValueType"] = { __ename__:true,__constructs__:null
	,TNull: {_hx_name:"TNull",_hx_index:0,__enum__:"ValueType",toString:$estr}
	,TInt: {_hx_name:"TInt",_hx_index:1,__enum__:"ValueType",toString:$estr}
	,TFloat: {_hx_name:"TFloat",_hx_index:2,__enum__:"ValueType",toString:$estr}
	,TBool: {_hx_name:"TBool",_hx_index:3,__enum__:"ValueType",toString:$estr}
	,TObject: {_hx_name:"TObject",_hx_index:4,__enum__:"ValueType",toString:$estr}
	,TFunction: {_hx_name:"TFunction",_hx_index:5,__enum__:"ValueType",toString:$estr}
	,TClass: ($_=function(c) { return {_hx_index:6,c:c,__enum__:"ValueType",toString:$estr}; },$_._hx_name="TClass",$_.__params__ = ["c"],$_)
	,TEnum: ($_=function(e) { return {_hx_index:7,e:e,__enum__:"ValueType",toString:$estr}; },$_._hx_name="TEnum",$_.__params__ = ["e"],$_)
	,TUnknown: {_hx_name:"TUnknown",_hx_index:8,__enum__:"ValueType",toString:$estr}
};
ValueType.__constructs__ = [ValueType.TNull,ValueType.TInt,ValueType.TFloat,ValueType.TBool,ValueType.TObject,ValueType.TFunction,ValueType.TClass,ValueType.TEnum,ValueType.TUnknown];
var Type = function() { };
Type.__name__ = true;
Type.typeof = function(v) {
	switch(typeof(v)) {
	case "boolean":
		return ValueType.TBool;
	case "function":
		if(v.__name__ || v.__ename__) {
			return ValueType.TObject;
		}
		return ValueType.TFunction;
	case "number":
		if(Math.ceil(v) == v % 2147483648.0) {
			return ValueType.TInt;
		}
		return ValueType.TFloat;
	case "object":
		if(v == null) {
			return ValueType.TNull;
		}
		var e = v.__enum__;
		if(e != null) {
			return ValueType.TEnum($hxEnums[e]);
		}
		var c = js_Boot.getClass(v);
		if(c != null) {
			return ValueType.TClass(c);
		}
		return ValueType.TObject;
	case "string":
		return ValueType.TClass(String);
	case "undefined":
		return ValueType.TNull;
	default:
		return ValueType.TUnknown;
	}
};
var esb_core_config_ConfigParser = function() {
};
$hx_exports["esb"]["core"]["config"]["ConfigParser"] = esb_core_config_ConfigParser;
esb_core_config_ConfigParser.__name__ = true;
esb_core_config_ConfigParser.fromFile = function(filename) {
	var contents = js_node_Fs.readFileSync(filename,{ encoding : "utf8"});
	var config = new esb_core_config_ConfigParser();
	return config.parse(contents);
};
esb_core_config_ConfigParser.prototype = {
	parse: function(jsonString) {
		var preprocessor = new esb_core_config__$ConfigParser_ConfigPreProcessor(jsonString);
		var json = preprocessor.process();
		var parser = new JsonParser_$0();
		parser.fromJson(JSON.stringify(json));
		var item = parser.value;
		this.printErrors(parser.errors);
		item.postProcess();
		return item;
	}
	,printErrors: function(errors) {
		if(errors != null) {
			var _g = 0;
			while(_g < errors.length) {
				var error = errors[_g];
				++_g;
				switch(error._hx_index) {
				case 0:
					var variable = error.variable;
					var expected = error.expected;
					var pos = error.pos;
					haxe_Log.trace("WARNING: json2object.IncorrectType(\"" + variable + "\", \"" + expected + "\")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 40, className : "esb.core.config.ConfigParser", methodName : "printErrors"});
					break;
				case 1:
					var value = error.value;
					var expected1 = error.expected;
					var pos1 = error.pos;
					haxe_Log.trace("WARNING: json2object.IncorrectEnumValue(\"" + value + "\", \"" + expected1 + "\")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 42, className : "esb.core.config.ConfigParser", methodName : "printErrors"});
					break;
				case 2:
					var value1 = error.value;
					var expected2 = error.expected;
					var pos2 = error.pos;
					haxe_Log.trace("WARNING: json2object.InvalidEnumConstructor(\"" + value1 + "\", \"" + expected2 + "\")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 44, className : "esb.core.config.ConfigParser", methodName : "printErrors"});
					break;
				case 3:
					var variable1 = error.variable;
					var pos3 = error.pos;
					break;
				case 4:
					var variable2 = error.variable;
					var pos4 = error.pos;
					haxe_Log.trace("WARNING: json2object.UnknownVariable(\"" + variable2 + "\")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 48, className : "esb.core.config.ConfigParser", methodName : "printErrors"});
					break;
				case 5:
					var message = error.message;
					var pos5 = error.pos;
					haxe_Log.trace("WARNING: json2object.ParserError(\"" + message + "\")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 50, className : "esb.core.config.ConfigParser", methodName : "printErrors"});
					break;
				case 6:
					var e = error.e;
					var pos6 = error.pos;
					break;
				}
			}
		}
	}
	,__class__: esb_core_config_ConfigParser
};
var esb_core_config__$ConfigParser_ConfigPreProcessor = function(jsonString) {
	this.jsonString = jsonString;
};
esb_core_config__$ConfigParser_ConfigPreProcessor.__name__ = true;
esb_core_config__$ConfigParser_ConfigPreProcessor.prototype = {
	process: function() {
		var _gthis = this;
		this.result = { };
		if(this.jsonString.indexOf("${") != -1 && this.jsonString.indexOf("}") != -1) {
			this.jsonString = esb_core_config__$ConfigParser_ConfigPreProcessor.reg.map(this.jsonString,function(f) {
				return _gthis.handleVar(f.matched(1));
			});
		}
		var json = JSON.parse(this.jsonString);
		this.processImportNodes(json);
		var result = this.processNodes(json);
		return result;
	}
	,handleVar: function(varName) {
		if(StringTools.startsWith(varName,"env:")) {
			var name = HxOverrides.substr(varName,"env:".length,null);
			if(process.env[name] == null) {
				haxe_Log.trace("WARNING: could not resolve environment variable: " + name,{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 94, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "handleVar"});
			} else {
				return process.env[name];
			}
		} else if(StringTools.startsWith(varName,"file:")) {
			var name = HxOverrides.substr(varName,"file:".length,null);
			var cwd = process.cwd();
			var fullPath = haxe_io_Path.normalize(cwd + "/" + name);
			if(!sys_FileSystem.isDirectory(fullPath) && sys_FileSystem.exists(fullPath)) {
				return StringTools.trim(js_node_Fs.readFileSync(fullPath,{ encoding : "utf8"}));
			} else {
				haxe_Log.trace("WARNING: could not read file: " + name,{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 105, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "handleVar"});
			}
		} else {
			haxe_Log.trace("WARNING: unknown variable type: " + varName,{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 108, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "handleVar"});
		}
		return null;
	}
	,processImportNodes: function(json) {
		var _g = 0;
		var _g1 = Reflect.fields(json);
		while(_g < _g1.length) {
			var nodeName = _g1[_g];
			++_g;
			var node = Reflect.field(json,nodeName);
			if(nodeName == "import") {
				this.handleImports(json,node);
			}
			if(Type.typeof(node)._hx_index == 4) {
				this.processImportNodes(node);
			}
		}
	}
	,processNode: function(node) {
		var result = null;
		var _g = Type.typeof(node);
		switch(_g._hx_index) {
		case 1:
			result = node;
			break;
		case 2:
			result = node;
			break;
		case 3:
			result = node;
			break;
		case 4:
			result = this.processNodes(node);
			break;
		case 6:
			switch(_g.c) {
			case Array:
				result = [];
				var nodeArray = node;
				var _g = 0;
				while(_g < nodeArray.length) {
					var item = nodeArray[_g];
					++_g;
					result.push(this.processNode(item));
				}
				break;
			case String:
				result = node;
				break;
			default:
				haxe_Log.trace(">>>>>>>>>>>>>>>>>>>>>>>>>>>> NO IDEA: ",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 148, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "processNode", customParams : [Type.typeof(node)]});
			}
			break;
		default:
			haxe_Log.trace(">>>>>>>>>>>>>>>>>>>>>>>>>>>> NO IDEA: ",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 148, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "processNode", customParams : [Type.typeof(node)]});
		}
		return result;
	}
	,processNodes: function(json) {
		var result = null;
		var _g = 0;
		var _g1 = Reflect.fields(json);
		while(_g < _g1.length) {
			var nodeName = _g1[_g];
			++_g;
			var node = Reflect.field(json,nodeName);
			if(result == null) {
				result = { };
			}
			if(nodeName != "import") {
				result[nodeName] = this.processNode(node);
			}
		}
		return result;
	}
	,handleImports: function(json,importNames) {
		var _g = 0;
		while(_g < importNames.length) {
			var importName = importNames[_g];
			++_g;
			this.handleImport(json,importName);
		}
	}
	,handleImport: function(json,importName) {
		if(importName.indexOf("*") != -1) {
			var regex = new EReg(importName,"gm");
			var cwd = process.cwd();
			var _g = 0;
			var _g1 = js_node_Fs.readdirSync(cwd);
			while(_g < _g1.length) {
				var item = _g1[_g];
				++_g;
				var fullPath = haxe_io_Path.normalize(cwd + "/" + item);
				if(!sys_FileSystem.isDirectory(fullPath) && regex.match(item)) {
					this.handleImport(json,item);
				}
			}
		} else {
			var cwd = process.cwd();
			var fullPath = haxe_io_Path.normalize(cwd + "/" + importName);
			if(!sys_FileSystem.exists(fullPath)) {
				haxe_Log.trace("WARNING: " + importName + " does not exist, skipping",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 188, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "handleImport"});
				return;
			}
			if(sys_FileSystem.isDirectory(fullPath)) {
				haxe_Log.trace("WARNING: " + importName + " is directory, skipping",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 192, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "handleImport"});
				return;
			}
			var jsonString = js_node_Fs.readFileSync(fullPath,{ encoding : "utf8"});
			var preprocessor = new esb_core_config__$ConfigParser_ConfigPreProcessor(jsonString);
			var importedJson = preprocessor.process();
			this.mergeJson(json,importedJson);
		}
	}
	,mergeJson: function(jsonDest,jsonSrc) {
		var _g = 0;
		var _g1 = Reflect.fields(jsonSrc);
		while(_g < _g1.length) {
			var fieldNameSrc = _g1[_g];
			++_g;
			var fieldExistsInDest = Object.prototype.hasOwnProperty.call(jsonDest,fieldNameSrc);
			var fieldValueSrc = Reflect.field(jsonSrc,fieldNameSrc);
			if(fieldExistsInDest) {
				var fieldTypeSrc = Type.typeof(fieldValueSrc);
				var fieldValueDest = Reflect.field(jsonDest,fieldNameSrc);
				var fieldTypeDest = Type.typeof(fieldValueDest);
				if(this.typeName(fieldValueSrc) != this.typeName(fieldValueDest)) {
					haxe_Log.trace("WARNING: type of fields dont match, skipping (field: " + fieldNameSrc + ", " + this.typeName(fieldValueSrc) + " != " + this.typeName(fieldValueDest) + ")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 212, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "mergeJson"});
				} else {
					switch(fieldTypeSrc._hx_index) {
					case 4:
						this.mergeJson(fieldValueDest,fieldValueSrc);
						break;
					case 6:
						if(fieldTypeSrc.c == Array) {
							var arraySrc = fieldValueSrc;
							var arrayDest = fieldValueDest;
							var _g2 = 0;
							while(_g2 < arraySrc.length) {
								var item = arraySrc[_g2];
								++_g2;
								arrayDest.push(item);
							}
						} else {
							haxe_Log.trace("WARNING: primitive values wont be merged / overwritten, skipping (field: " + fieldNameSrc + ", type: " + this.typeName(fieldValueSrc) + ")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 224, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "mergeJson"});
						}
						break;
					default:
						haxe_Log.trace("WARNING: primitive values wont be merged / overwritten, skipping (field: " + fieldNameSrc + ", type: " + this.typeName(fieldValueSrc) + ")",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 224, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "mergeJson"});
					}
				}
			} else {
				jsonDest[fieldNameSrc] = fieldValueSrc;
			}
		}
	}
	,typeName: function(o) {
		var _g = Type.typeof(o);
		switch(_g._hx_index) {
		case 1:
			return "int";
		case 2:
			return "float";
		case 3:
			return "bool";
		case 4:
			return "object";
		case 6:
			switch(_g.c) {
			case Array:
				return "array";
			case String:
				return "string";
			default:
				haxe_Log.trace(">>>>>>>>>>>>>>>>>>>>>>>>>>>> NO IDEA: ",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 248, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "typeName", customParams : [Type.typeof(o)]});
				return "unknown";
			}
			break;
		default:
			haxe_Log.trace(">>>>>>>>>>>>>>>>>>>>>>>>>>>> NO IDEA: ",{ fileName : "./esb/core/config/ConfigParser.hx", lineNumber : 248, className : "esb.core.config._ConfigParser.ConfigPreProcessor", methodName : "typeName", customParams : [Type.typeof(o)]});
			return "unknown";
		}
	}
	,__class__: esb_core_config__$ConfigParser_ConfigPreProcessor
};
var esb_core_config_sections_BundleConfig = function() {
	this._parent = null;
	this._properties = new haxe_ds_StringMap();
};
$hx_exports["esb"]["core"]["config"]["sections"]["BundleConfig"] = esb_core_config_sections_BundleConfig;
esb_core_config_sections_BundleConfig.__name__ = true;
esb_core_config_sections_BundleConfig.prototype = {
	hasPrefix: function(prefix,producer) {
		if(this.prefixes == null) {
			return false;
		}
		if(!Object.prototype.hasOwnProperty.call(this.prefixes.h,prefix)) {
			return false;
		}
		var prefixConfig = this.prefixes.h[prefix];
		if(producer && prefixConfig.producer == null) {
			return false;
		}
		if(!producer && prefixConfig.consumer == null) {
			return false;
		}
		return true;
	}
	,get_parent: function() {
		return this._parent;
	}
	,set_parent: function(value) {
		this._parent = value;
		var h = this.prefixes.h;
		var prefixName_h = h;
		var prefixName_keys = Object.keys(h);
		var prefixName_length = prefixName_keys.length;
		var prefixName_current = 0;
		while(prefixName_current < prefixName_length) {
			var prefixName = prefixName_keys[prefixName_current++];
			var prefix = this.prefixes.h[prefixName];
			prefix.set_parent(this);
		}
		return value;
	}
	,postProcess: function() {
		this.properties = new esb_core_config_sections_PropertiesConfig(this._properties);
		this.properties.parentProperties = this._parent.properties;
		this.properties.postProcess();
		if(this.name != null) {
			var s = this.name;
			var properties = this.properties;
			if(s.indexOf("{{") != -1 && s.indexOf("}}") != -1) {
				s = esb_core_config_sections_EsbConfig.reg.map(s,function(f) {
					var v = properties.get(f.matched(1));
					if(v == s && properties.parentProperties != null) {
						v = properties.parentProperties.get(f.matched(1));
					}
					if(v == null) {
						haxe_Log.trace("WARNING: could not resolve property placholder {{" + f.matched(1) + "}}",{ fileName : "./esb/core/config/sections/EsbConfig.hx", lineNumber : 127, className : "esb.core.config.sections.EsbConfig", methodName : "applyPropertiesTo"});
						return "";
					}
					return v;
				});
			}
			this.name = s;
		}
		if(this.bundleFile != null) {
			var s1 = this.bundleFile;
			var properties1 = this.properties;
			if(s1.indexOf("{{") != -1 && s1.indexOf("}}") != -1) {
				s1 = esb_core_config_sections_EsbConfig.reg.map(s1,function(f) {
					var v = properties1.get(f.matched(1));
					if(v == s1 && properties1.parentProperties != null) {
						v = properties1.parentProperties.get(f.matched(1));
					}
					if(v == null) {
						haxe_Log.trace("WARNING: could not resolve property placholder {{" + f.matched(1) + "}}",{ fileName : "./esb/core/config/sections/EsbConfig.hx", lineNumber : 127, className : "esb.core.config.sections.EsbConfig", methodName : "applyPropertiesTo"});
						return "";
					}
					return v;
				});
			}
			this.bundleFile = s1;
		}
		var h = this.prefixes.h;
		var prefixName_h = h;
		var prefixName_keys = Object.keys(h);
		var prefixName_length = prefixName_keys.length;
		var prefixName_current = 0;
		while(prefixName_current < prefixName_length) {
			var prefixName = prefixName_keys[prefixName_current++];
			var prefix = this.prefixes.h[prefixName];
			prefix.postProcess();
		}
	}
	,__class__: esb_core_config_sections_BundleConfig
};
var esb_core_config_sections_BundlePrefixCommonConfig = function() {
	this._parent = null;
};
$hx_exports["esb"]["core"]["config"]["sections"]["BundlePrefixCommonConfig"] = esb_core_config_sections_BundlePrefixCommonConfig;
esb_core_config_sections_BundlePrefixCommonConfig.__name__ = true;
esb_core_config_sections_BundlePrefixCommonConfig.prototype = {
	get_parent: function() {
		return this._parent;
	}
	,set_parent: function(value) {
		this._parent = value;
		return value;
	}
	,get_bundle: function() {
		return this._parent._parent;
	}
	,postProcess: function() {
		if(this.className != null) {
			var s = this.className;
			var properties = this.get_bundle().properties;
			if(s.indexOf("{{") != -1 && s.indexOf("}}") != -1) {
				s = esb_core_config_sections_EsbConfig.reg.map(s,function(f) {
					var v = properties.get(f.matched(1));
					if(v == s && properties.parentProperties != null) {
						v = properties.parentProperties.get(f.matched(1));
					}
					if(v == null) {
						haxe_Log.trace("WARNING: could not resolve property placholder {{" + f.matched(1) + "}}",{ fileName : "./esb/core/config/sections/EsbConfig.hx", lineNumber : 127, className : "esb.core.config.sections.EsbConfig", methodName : "applyPropertiesTo"});
						return "";
					}
					return v;
				});
			}
			this.className = s;
		}
	}
	,__class__: esb_core_config_sections_BundlePrefixCommonConfig
};
var esb_core_config_sections_BundlePrefixConfig = function() {
	this._parent = null;
};
$hx_exports["esb"]["core"]["config"]["sections"]["BundlePrefixConfig"] = esb_core_config_sections_BundlePrefixConfig;
esb_core_config_sections_BundlePrefixConfig.__name__ = true;
esb_core_config_sections_BundlePrefixConfig.prototype = {
	get_parent: function() {
		return this._parent;
	}
	,set_parent: function(value) {
		this._parent = value;
		if(this.consumer != null) {
			this.consumer.set_parent(this);
		}
		if(this.producer != null) {
			this.producer.set_parent(this);
		}
		return value;
	}
	,postProcess: function() {
		if(this.consumer != null) {
			this.consumer.postProcess();
		}
		if(this.producer != null) {
			this.producer.postProcess();
		}
	}
	,__class__: esb_core_config_sections_BundlePrefixConfig
};
var esb_core_config_sections_BundlePrefixConsumerConfig = function() {
	esb_core_config_sections_BundlePrefixCommonConfig.call(this);
};
$hx_exports["esb"]["core"]["config"]["sections"]["BundlePrefixConsumerConfig"] = esb_core_config_sections_BundlePrefixConsumerConfig;
esb_core_config_sections_BundlePrefixConsumerConfig.__name__ = true;
esb_core_config_sections_BundlePrefixConsumerConfig.__super__ = esb_core_config_sections_BundlePrefixCommonConfig;
esb_core_config_sections_BundlePrefixConsumerConfig.prototype = $extend(esb_core_config_sections_BundlePrefixCommonConfig.prototype,{
	__class__: esb_core_config_sections_BundlePrefixConsumerConfig
});
var esb_core_config_sections_BundlePrefixProducerConfig = function() {
	esb_core_config_sections_BundlePrefixCommonConfig.call(this);
};
$hx_exports["esb"]["core"]["config"]["sections"]["BundlePrefixProducerConfig"] = esb_core_config_sections_BundlePrefixProducerConfig;
esb_core_config_sections_BundlePrefixProducerConfig.__name__ = true;
esb_core_config_sections_BundlePrefixProducerConfig.__super__ = esb_core_config_sections_BundlePrefixCommonConfig;
esb_core_config_sections_BundlePrefixProducerConfig.prototype = $extend(esb_core_config_sections_BundlePrefixCommonConfig.prototype,{
	__class__: esb_core_config_sections_BundlePrefixProducerConfig
});
var esb_core_config_sections_EsbConfig = function() {
	this._properties = new haxe_ds_StringMap();
	this.queues = new haxe_ds_StringMap();
	this.bundles = new haxe_ds_StringMap();
};
$hx_exports["esb"]["core"]["config"]["sections"]["EsbConfig"] = esb_core_config_sections_EsbConfig;
esb_core_config_sections_EsbConfig.__name__ = true;
esb_core_config_sections_EsbConfig.applyPropertiesTo = function(s,properties) {
	if(s.indexOf("{{") != -1 && s.indexOf("}}") != -1) {
		s = esb_core_config_sections_EsbConfig.reg.map(s,function(f) {
			var v = properties.get(f.matched(1));
			if(v == s && properties.parentProperties != null) {
				v = properties.parentProperties.get(f.matched(1));
			}
			if(v == null) {
				haxe_Log.trace("WARNING: could not resolve property placholder {{" + f.matched(1) + "}}",{ fileName : "./esb/core/config/sections/EsbConfig.hx", lineNumber : 127, className : "esb.core.config.sections.EsbConfig", methodName : "applyPropertiesTo"});
				return "";
			}
			return v;
		});
	}
	return s;
};
esb_core_config_sections_EsbConfig.prototype = {
	findBundleFromPrefix: function(prefix,producer) {
		if(this.bundles == null) {
			return null;
		}
		var foundBundle = null;
		var h = this.bundles.h;
		var bundleName_h = h;
		var bundleName_keys = Object.keys(h);
		var bundleName_length = bundleName_keys.length;
		var bundleName_current = 0;
		while(bundleName_current < bundleName_length) {
			var bundleName = bundleName_keys[bundleName_current++];
			var bundle = this.bundles.h[bundleName];
			if(bundle.hasPrefix(prefix,producer)) {
				foundBundle = bundle;
				break;
			}
		}
		return foundBundle;
	}
	,findPrefix: function(prefix,producer) {
		var bundle = this.findBundleFromPrefix(prefix,producer);
		if(bundle == null) {
			return null;
		}
		if(producer) {
			return bundle.prefixes.h[prefix].producer;
		}
		if(!producer) {
			return bundle.prefixes.h[prefix].consumer;
		}
		return null;
	}
	,postProcess: function() {
		var bundlesToRemove = [];
		var h = this.bundles.h;
		var bundleName_h = h;
		var bundleName_keys = Object.keys(h);
		var bundleName_length = bundleName_keys.length;
		var bundleName_current = 0;
		while(bundleName_current < bundleName_length) {
			var bundleName = bundleName_keys[bundleName_current++];
			var bundle = this.bundles.h[bundleName];
			if(bundle == null) {
				bundlesToRemove.push(bundleName);
			}
		}
		var _g = 0;
		while(_g < bundlesToRemove.length) {
			var bundleName = bundlesToRemove[_g];
			++_g;
			var _this = this.bundles;
			if(Object.prototype.hasOwnProperty.call(_this.h,bundleName)) {
				delete(_this.h[bundleName]);
			}
		}
		var h = this.bundles.h;
		var bundleName_h = h;
		var bundleName_keys = Object.keys(h);
		var bundleName_length = bundleName_keys.length;
		var bundleName_current = 0;
		while(bundleName_current < bundleName_length) {
			var bundleName = bundleName_keys[bundleName_current++];
			var bundle = this.bundles.h[bundleName];
			if(bundle == null) {
				continue;
			}
			bundle.set_parent(this);
		}
		var queuesToRemove = [];
		var h = this.queues.h;
		var queueName_h = h;
		var queueName_keys = Object.keys(h);
		var queueName_length = queueName_keys.length;
		var queueName_current = 0;
		while(queueName_current < queueName_length) {
			var queueName = queueName_keys[queueName_current++];
			var queue = this.queues.h[queueName];
			if(queue == null) {
				queuesToRemove.push(queueName);
			}
		}
		var _g = 0;
		while(_g < queuesToRemove.length) {
			var queueName = queuesToRemove[_g];
			++_g;
			var _this = this.queues;
			if(Object.prototype.hasOwnProperty.call(_this.h,queueName)) {
				delete(_this.h[queueName]);
			}
		}
		var h = this.queues.h;
		var queueName_h = h;
		var queueName_keys = Object.keys(h);
		var queueName_length = queueName_keys.length;
		var queueName_current = 0;
		while(queueName_current < queueName_length) {
			var queueName = queueName_keys[queueName_current++];
			var queue = this.queues.h[queueName];
			if(queue == null) {
				continue;
			}
			queue.set_parent(this);
		}
		this.properties = new esb_core_config_sections_PropertiesConfig(this._properties);
		this.properties.postProcess();
		var h = this.bundles.h;
		var bundleName_h = h;
		var bundleName_keys = Object.keys(h);
		var bundleName_length = bundleName_keys.length;
		var bundleName_current = 0;
		while(bundleName_current < bundleName_length) {
			var bundleName = bundleName_keys[bundleName_current++];
			var bundle = this.bundles.h[bundleName];
			if(bundle == null) {
				continue;
			}
			bundle.postProcess();
		}
		var h = this.queues.h;
		var queueName_h = h;
		var queueName_keys = Object.keys(h);
		var queueName_length = queueName_keys.length;
		var queueName_current = 0;
		while(queueName_current < queueName_length) {
			var queueName = queueName_keys[queueName_current++];
			var queue = this.queues.h[queueName];
			if(queue == null) {
				continue;
			}
			queue.postProcess();
		}
	}
	,__class__: esb_core_config_sections_EsbConfig
};
var esb_core_config_sections_PropertiesConfig = function(items) {
	this.parentProperties = null;
	this.items = new haxe_ds_StringMap();
	this.items = items;
};
$hx_exports["esb"]["core"]["config"]["sections"]["PropertiesConfig"] = esb_core_config_sections_PropertiesConfig;
esb_core_config_sections_PropertiesConfig.__name__ = true;
esb_core_config_sections_PropertiesConfig.prototype = {
	get: function(name,defaultValue,params) {
		if(this.items == null) {
			if(this.parentProperties != null) {
				return this.parentProperties.get(name,defaultValue,params);
			}
			return defaultValue;
		}
		if(!Object.prototype.hasOwnProperty.call(this.items.h,name)) {
			if(this.parentProperties != null) {
				return this.parentProperties.get(name,defaultValue,params);
			}
			return defaultValue;
		}
		var v = this.items.h[name];
		if(params != null && v.indexOf("{") != -1 && v.indexOf("}") != -1) {
			v = esb_core_config_sections_PropertiesConfig.reg.map(v,function(f) {
				var key = f.matched(1);
				var v = params.h[key];
				if(v == null) {
					haxe_Log.trace("WARNING: could not resolve interpolated value {" + f.matched(1) + "}",{ fileName : "./esb/core/config/sections/PropertiesConfig.hx", lineNumber : 45, className : "esb.core.config.sections.PropertiesConfig", methodName : "get"});
					return "";
				}
				return v;
			});
		}
		return v;
	}
	,keys: function() {
		if(this.items == null) {
			return null;
		}
		return new haxe_ds__$StringMap_StringMapKeyIterator(this.items.h);
	}
	,postProcess: function() {
		if(this.items == null) {
			return;
		}
		var h = this.items.h;
		var item_h = h;
		var item_keys = Object.keys(h);
		var item_length = item_keys.length;
		var item_current = 0;
		while(item_current < item_length) {
			var item = item_keys[item_current++];
			var value = this.items.h[item];
			var s = [value];
			var properties = [this];
			if(s[0].indexOf("{{") != -1 && s[0].indexOf("}}") != -1) {
				s[0] = esb_core_config_sections_EsbConfig.reg.map(s[0],(function(properties,s) {
					return function(f) {
						var v = properties[0].get(f.matched(1));
						if(v == s[0] && properties[0].parentProperties != null) {
							v = properties[0].parentProperties.get(f.matched(1));
						}
						if(v == null) {
							haxe_Log.trace("WARNING: could not resolve property placholder {{" + f.matched(1) + "}}",{ fileName : "./esb/core/config/sections/EsbConfig.hx", lineNumber : 127, className : "esb.core.config.sections.EsbConfig", methodName : "applyPropertiesTo"});
							return "";
						}
						return v;
					};
				})(properties,s));
			}
			value = s[0];
			this.items.h[item] = value;
		}
		var h = this.items.h;
		var item_h = h;
		var item_keys = Object.keys(h);
		var item_length = item_keys.length;
		var item_current = 0;
		while(item_current < item_length) {
			var item = item_keys[item_current++];
			var value = this.items.h[item];
			var s1 = [value];
			var properties1 = [this];
			if(s1[0].indexOf("{{") != -1 && s1[0].indexOf("}}") != -1) {
				s1[0] = esb_core_config_sections_EsbConfig.reg.map(s1[0],(function(properties,s) {
					return function(f) {
						var v = properties[0].get(f.matched(1));
						if(v == s[0] && properties[0].parentProperties != null) {
							v = properties[0].parentProperties.get(f.matched(1));
						}
						if(v == null) {
							haxe_Log.trace("WARNING: could not resolve property placholder {{" + f.matched(1) + "}}",{ fileName : "./esb/core/config/sections/EsbConfig.hx", lineNumber : 127, className : "esb.core.config.sections.EsbConfig", methodName : "applyPropertiesTo"});
							return "";
						}
						return v;
					};
				})(properties1,s1));
			}
			value = s1[0];
			this.items.h[item] = value;
		}
	}
	,__class__: esb_core_config_sections_PropertiesConfig
};
var esb_core_config_sections_PropertyConfig = function() {
};
$hx_exports["esb"]["core"]["config"]["sections"]["PropertyConfig"] = esb_core_config_sections_PropertyConfig;
esb_core_config_sections_PropertyConfig.__name__ = true;
esb_core_config_sections_PropertyConfig.prototype = {
	__class__: esb_core_config_sections_PropertyConfig
};
var esb_core_config_sections_QueueCommonConfig = function() {
	this._parent = null;
	this._properties = new haxe_ds_StringMap();
};
$hx_exports["esb"]["core"]["config"]["sections"]["QueueCommonConfig"] = esb_core_config_sections_QueueCommonConfig;
esb_core_config_sections_QueueCommonConfig.__name__ = true;
esb_core_config_sections_QueueCommonConfig.prototype = {
	get_parent: function() {
		return this._parent;
	}
	,set_parent: function(value) {
		this._parent = value;
		return value;
	}
	,postProcess: function() {
		this.properties = new esb_core_config_sections_PropertiesConfig(this._properties);
		this.properties.parentProperties = this._parent.properties;
		this.properties.postProcess();
		if(this.className != null) {
			var s = this.className;
			var properties = this.properties;
			if(s.indexOf("{{") != -1 && s.indexOf("}}") != -1) {
				s = esb_core_config_sections_EsbConfig.reg.map(s,function(f) {
					var v = properties.get(f.matched(1));
					if(v == s && properties.parentProperties != null) {
						v = properties.parentProperties.get(f.matched(1));
					}
					if(v == null) {
						haxe_Log.trace("WARNING: could not resolve property placholder {{" + f.matched(1) + "}}",{ fileName : "./esb/core/config/sections/EsbConfig.hx", lineNumber : 127, className : "esb.core.config.sections.EsbConfig", methodName : "applyPropertiesTo"});
						return "";
					}
					return v;
				});
			}
			this.className = s;
		}
	}
	,__class__: esb_core_config_sections_QueueCommonConfig
};
var esb_core_config_sections_QueueConfig = function() {
	this._parent = null;
	this._properties = new haxe_ds_StringMap();
};
$hx_exports["esb"]["core"]["config"]["sections"]["QueueConfig"] = esb_core_config_sections_QueueConfig;
esb_core_config_sections_QueueConfig.__name__ = true;
esb_core_config_sections_QueueConfig.prototype = {
	get_parent: function() {
		return this._parent;
	}
	,set_parent: function(value) {
		this._parent = value;
		if(this.consumer != null) {
			this.consumer.set_parent(this);
		}
		if(this.producer != null) {
			this.producer.set_parent(this);
		}
		return value;
	}
	,postProcess: function() {
		this.properties = new esb_core_config_sections_PropertiesConfig(this._properties);
		this.properties.parentProperties = this._parent.properties;
		this.properties.postProcess();
		if(this.consumer != null) {
			this.consumer.postProcess();
		}
		if(this.producer != null) {
			this.producer.postProcess();
		}
	}
	,__class__: esb_core_config_sections_QueueConfig
};
var esb_core_config_sections_QueueConsumerConfig = function() {
	esb_core_config_sections_QueueCommonConfig.call(this);
};
$hx_exports["esb"]["core"]["config"]["sections"]["QueueConsumerConfig"] = esb_core_config_sections_QueueConsumerConfig;
esb_core_config_sections_QueueConsumerConfig.__name__ = true;
esb_core_config_sections_QueueConsumerConfig.__super__ = esb_core_config_sections_QueueCommonConfig;
esb_core_config_sections_QueueConsumerConfig.prototype = $extend(esb_core_config_sections_QueueCommonConfig.prototype,{
	__class__: esb_core_config_sections_QueueConsumerConfig
});
var esb_core_config_sections_QueueProducerConfig = function() {
	esb_core_config_sections_QueueCommonConfig.call(this);
};
$hx_exports["esb"]["core"]["config"]["sections"]["QueueProducerConfig"] = esb_core_config_sections_QueueProducerConfig;
esb_core_config_sections_QueueProducerConfig.__name__ = true;
esb_core_config_sections_QueueProducerConfig.__super__ = esb_core_config_sections_QueueCommonConfig;
esb_core_config_sections_QueueProducerConfig.prototype = $extend(esb_core_config_sections_QueueCommonConfig.prototype,{
	__class__: esb_core_config_sections_QueueProducerConfig
});
var haxe_IMap = function() { };
haxe_IMap.__name__ = true;
haxe_IMap.__isInterface__ = true;
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
	,get_native: function() {
		return this.__nativeException;
	}
	,__class__: haxe_Exception
});
var haxe_Log = function() { };
haxe_Log.__name__ = true;
haxe_Log.formatOutput = function(v,infos) {
	var str = Std.string(v);
	if(infos == null) {
		return str;
	}
	var pstr = infos.fileName + ":" + infos.lineNumber;
	if(infos.customParams != null) {
		var _g = 0;
		var _g1 = infos.customParams;
		while(_g < _g1.length) {
			var v = _g1[_g];
			++_g;
			str += ", " + Std.string(v);
		}
	}
	return pstr + ": " + str;
};
haxe_Log.trace = function(v,infos) {
	var str = haxe_Log.formatOutput(v,infos);
	if(typeof(console) != "undefined" && console.log != null) {
		console.log(str);
	}
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
	,__class__: haxe_ValueException
});
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	__class__: haxe_ds_StringMap
};
var haxe_ds__$StringMap_StringMapKeyIterator = function(h) {
	this.h = h;
	this.keys = Object.keys(h);
	this.length = this.keys.length;
	this.current = 0;
};
haxe_ds__$StringMap_StringMapKeyIterator.__name__ = true;
haxe_ds__$StringMap_StringMapKeyIterator.prototype = {
	hasNext: function() {
		return this.current < this.length;
	}
	,next: function() {
		return this.keys[this.current++];
	}
	,__class__: haxe_ds__$StringMap_StringMapKeyIterator
};
var haxe_io_Path = function() { };
haxe_io_Path.__name__ = true;
haxe_io_Path.normalize = function(path) {
	var slash = "/";
	path = path.split("\\").join(slash);
	if(path == slash) {
		return slash;
	}
	var target = [];
	var _g = 0;
	var _g1 = path.split(slash);
	while(_g < _g1.length) {
		var token = _g1[_g];
		++_g;
		if(token == ".." && target.length > 0 && target[target.length - 1] != "..") {
			target.pop();
		} else if(token == "") {
			if(target.length > 0 || HxOverrides.cca(path,0) == 47) {
				target.push(token);
			}
		} else if(token != ".") {
			target.push(token);
		}
	}
	var tmp = target.join(slash);
	var acc_b = "";
	var colon = false;
	var slashes = false;
	var _g_offset = 0;
	var _g_s = tmp;
	while(_g_offset < _g_s.length) {
		var s = _g_s;
		var index = _g_offset++;
		var c = s.charCodeAt(index);
		if(c >= 55296 && c <= 56319) {
			c = c - 55232 << 10 | s.charCodeAt(index + 1) & 1023;
		}
		var c1 = c;
		if(c1 >= 65536) {
			++_g_offset;
		}
		var c2 = c1;
		switch(c2) {
		case 47:
			if(!colon) {
				slashes = true;
			} else {
				var i = c2;
				colon = false;
				if(slashes) {
					acc_b += "/";
					slashes = false;
				}
				acc_b += String.fromCodePoint(i);
			}
			break;
		case 58:
			acc_b += ":";
			colon = true;
			break;
		default:
			var i1 = c2;
			colon = false;
			if(slashes) {
				acc_b += "/";
				slashes = false;
			}
			acc_b += String.fromCodePoint(i1);
		}
	}
	return acc_b;
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var hxjsonast_Error = function(message,pos) {
	this.message = message;
	this.pos = pos;
};
hxjsonast_Error.__name__ = true;
hxjsonast_Error.prototype = {
	__class__: hxjsonast_Error
};
var hxjsonast_Json = function(value,pos) {
	this.value = value;
	this.pos = pos;
};
hxjsonast_Json.__name__ = true;
hxjsonast_Json.prototype = {
	__class__: hxjsonast_Json
};
var hxjsonast_JsonValue = $hxEnums["hxjsonast.JsonValue"] = { __ename__:true,__constructs__:null
	,JString: ($_=function(s) { return {_hx_index:0,s:s,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_._hx_name="JString",$_.__params__ = ["s"],$_)
	,JNumber: ($_=function(s) { return {_hx_index:1,s:s,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_._hx_name="JNumber",$_.__params__ = ["s"],$_)
	,JObject: ($_=function(fields) { return {_hx_index:2,fields:fields,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_._hx_name="JObject",$_.__params__ = ["fields"],$_)
	,JArray: ($_=function(values) { return {_hx_index:3,values:values,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_._hx_name="JArray",$_.__params__ = ["values"],$_)
	,JBool: ($_=function(b) { return {_hx_index:4,b:b,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_._hx_name="JBool",$_.__params__ = ["b"],$_)
	,JNull: {_hx_name:"JNull",_hx_index:5,__enum__:"hxjsonast.JsonValue",toString:$estr}
};
hxjsonast_JsonValue.__constructs__ = [hxjsonast_JsonValue.JString,hxjsonast_JsonValue.JNumber,hxjsonast_JsonValue.JObject,hxjsonast_JsonValue.JArray,hxjsonast_JsonValue.JBool,hxjsonast_JsonValue.JNull];
var hxjsonast_JObjectField = function(name,namePos,value) {
	this.name = name;
	this.namePos = namePos;
	this.value = value;
};
hxjsonast_JObjectField.__name__ = true;
hxjsonast_JObjectField.prototype = {
	__class__: hxjsonast_JObjectField
};
var hxjsonast_Parser = function(source,filename) {
	this.source = source;
	this.filename = filename;
	this.pos = 0;
};
hxjsonast_Parser.__name__ = true;
hxjsonast_Parser.prototype = {
	doParse: function() {
		var result = this.parseRec();
		var c;
		while(true) {
			c = this.source.charCodeAt(this.pos++);
			var c1 = c;
			if(!(c1 == c1)) {
				break;
			}
			switch(c) {
			case 9:case 10:case 13:case 32:
				break;
			default:
				this.invalidChar();
			}
		}
		return result;
	}
	,parseRec: function() {
		while(true) {
			var c = this.source.charCodeAt(this.pos++);
			switch(c) {
			case 9:case 10:case 13:case 32:
				break;
			case 34:
				var save = this.pos;
				var s = this.parseString();
				return new hxjsonast_Json(hxjsonast_JsonValue.JString(s),new hxjsonast_Position(this.filename,save - 1,this.pos));
			case 45:case 48:case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:
				var start = this.pos - 1;
				var minus = c == 45;
				var digit = !minus;
				var zero = c == 48;
				var point = false;
				var e = false;
				var pm = false;
				var end = false;
				do switch(this.source.charCodeAt(this.pos++)) {
				case 43:case 45:
					if(!e || pm) {
						this.invalidNumber(start);
					}
					digit = false;
					pm = true;
					break;
				case 46:
					if(minus || point || e) {
						this.invalidNumber(start);
					}
					digit = false;
					point = true;
					break;
				case 48:
					if(zero && !point) {
						this.invalidNumber(start);
					}
					if(minus) {
						minus = false;
						zero = true;
					}
					digit = true;
					break;
				case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:
					if(zero && !point) {
						this.invalidNumber(start);
					}
					if(minus) {
						minus = false;
					}
					digit = true;
					zero = false;
					break;
				case 69:case 101:
					if(minus || zero || e) {
						this.invalidNumber(start);
					}
					digit = false;
					e = true;
					break;
				default:
					if(!digit) {
						this.invalidNumber(start);
					}
					this.pos--;
					end = true;
				} while(!end);
				var s1 = HxOverrides.substr(this.source,start,this.pos - start);
				return new hxjsonast_Json(hxjsonast_JsonValue.JNumber(s1),new hxjsonast_Position(this.filename,start,this.pos));
			case 91:
				var values = [];
				var comma = null;
				var startPos = this.pos - 1;
				while(true) switch(this.source.charCodeAt(this.pos++)) {
				case 9:case 10:case 13:case 32:
					break;
				case 44:
					if(comma) {
						comma = false;
					} else {
						this.invalidChar();
					}
					break;
				case 93:
					if(comma == false) {
						this.invalidChar();
					}
					return new hxjsonast_Json(hxjsonast_JsonValue.JArray(values),new hxjsonast_Position(this.filename,startPos,this.pos));
				default:
					if(comma) {
						this.invalidChar();
					}
					this.pos--;
					values.push(this.parseRec());
					comma = true;
				}
				break;
			case 102:
				var save1 = this.pos;
				if(this.source.charCodeAt(this.pos++) != 97 || this.source.charCodeAt(this.pos++) != 108 || this.source.charCodeAt(this.pos++) != 115 || this.source.charCodeAt(this.pos++) != 101) {
					this.pos = save1;
					this.invalidChar();
				}
				return new hxjsonast_Json(hxjsonast_JsonValue.JBool(false),new hxjsonast_Position(this.filename,save1 - 1,this.pos));
			case 110:
				var save2 = this.pos;
				if(this.source.charCodeAt(this.pos++) != 117 || this.source.charCodeAt(this.pos++) != 108 || this.source.charCodeAt(this.pos++) != 108) {
					this.pos = save2;
					this.invalidChar();
				}
				return new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position(this.filename,save2 - 1,this.pos));
			case 116:
				var save3 = this.pos;
				if(this.source.charCodeAt(this.pos++) != 114 || this.source.charCodeAt(this.pos++) != 117 || this.source.charCodeAt(this.pos++) != 101) {
					this.pos = save3;
					this.invalidChar();
				}
				return new hxjsonast_Json(hxjsonast_JsonValue.JBool(true),new hxjsonast_Position(this.filename,save3 - 1,this.pos));
			case 123:
				var fields = [];
				var names_h = Object.create(null);
				var field = null;
				var fieldPos = null;
				var comma1 = null;
				var startPos1 = this.pos - 1;
				while(true) switch(this.source.charCodeAt(this.pos++)) {
				case 9:case 10:case 13:case 32:
					break;
				case 34:
					if(field != null || comma1) {
						this.invalidChar();
					}
					var fieldStartPos = this.pos - 1;
					field = this.parseString();
					fieldPos = new hxjsonast_Position(this.filename,fieldStartPos,this.pos);
					if(Object.prototype.hasOwnProperty.call(names_h,field)) {
						throw haxe_Exception.thrown(new hxjsonast_Error("Duplicate field name \"" + field + "\"",fieldPos));
					} else {
						names_h[field] = true;
					}
					break;
				case 44:
					if(comma1) {
						comma1 = false;
					} else {
						this.invalidChar();
					}
					break;
				case 58:
					if(field == null) {
						this.invalidChar();
					}
					fields.push(new hxjsonast_JObjectField(field,fieldPos,this.parseRec()));
					field = null;
					fieldPos = null;
					comma1 = true;
					break;
				case 125:
					if(field != null || comma1 == false) {
						this.invalidChar();
					}
					return new hxjsonast_Json(hxjsonast_JsonValue.JObject(fields),new hxjsonast_Position(this.filename,startPos1,this.pos));
				default:
					this.invalidChar();
				}
				break;
			default:
				this.invalidChar();
			}
		}
	}
	,parseString: function() {
		var start = this.pos;
		var buf = null;
		while(true) {
			var c = this.source.charCodeAt(this.pos++);
			if(c == 34) {
				break;
			}
			if(c == 92) {
				if(buf == null) {
					buf = new StringBuf();
				}
				var s = this.source;
				var len = this.pos - start - 1;
				buf.b += len == null ? HxOverrides.substr(s,start,null) : HxOverrides.substr(s,start,len);
				c = this.source.charCodeAt(this.pos++);
				switch(c) {
				case 34:case 47:case 92:
					buf.b += String.fromCodePoint(c);
					break;
				case 98:
					buf.b += String.fromCodePoint(8);
					break;
				case 102:
					buf.b += String.fromCodePoint(12);
					break;
				case 110:
					buf.b += String.fromCodePoint(10);
					break;
				case 114:
					buf.b += String.fromCodePoint(13);
					break;
				case 116:
					buf.b += String.fromCodePoint(9);
					break;
				case 117:
					var uc = Std.parseInt("0x" + HxOverrides.substr(this.source,this.pos,4));
					this.pos += 4;
					buf.b += String.fromCodePoint(uc);
					break;
				default:
					throw haxe_Exception.thrown(new hxjsonast_Error("Invalid escape sequence \\" + String.fromCodePoint(c),new hxjsonast_Position(this.filename,this.pos - 2,this.pos)));
				}
				start = this.pos;
			} else if(c != c) {
				this.pos--;
				throw haxe_Exception.thrown(new hxjsonast_Error("Unclosed string",new hxjsonast_Position(this.filename,start - 1,this.pos)));
			}
		}
		if(buf == null) {
			return HxOverrides.substr(this.source,start,this.pos - start - 1);
		} else {
			var s = this.source;
			var len = this.pos - start - 1;
			buf.b += len == null ? HxOverrides.substr(s,start,null) : HxOverrides.substr(s,start,len);
			return buf.b;
		}
	}
	,invalidChar: function() {
		this.pos--;
		throw haxe_Exception.thrown(new hxjsonast_Error("Invalid character: " + this.source.charAt(this.pos),new hxjsonast_Position(this.filename,this.pos,this.pos + 1)));
	}
	,invalidNumber: function(start) {
		throw haxe_Exception.thrown(new hxjsonast_Error("Invalid number: " + this.source.substring(start,this.pos),new hxjsonast_Position(this.filename,start,this.pos)));
	}
	,__class__: hxjsonast_Parser
};
var hxjsonast_Position = function(file,min,max) {
	this.file = file;
	this.min = min;
	this.max = max;
};
hxjsonast_Position.__name__ = true;
hxjsonast_Position.prototype = {
	__class__: hxjsonast_Position
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var con = e.__constructs__[o._hx_index];
			var n = con._hx_name;
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g = 0;
		var _g1 = intf.length;
		while(_g < _g1) {
			var i = _g++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		return ((o) instanceof Array);
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return o != null;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return ((o | 0) === o);
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(js_Boot.__downcastCheck(o,cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(((o) instanceof cl)) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ != null ? $hxEnums[o.__enum__] == cl : false;
	}
};
js_Boot.__downcastCheck = function(o,cl) {
	if(!((o) instanceof cl)) {
		if(cl.__isInterface__) {
			return js_Boot.__interfLoop(js_Boot.getClass(o),cl);
		} else {
			return false;
		}
	} else {
		return true;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var js_node_Fs = require("fs");
var json2object_Error = $hxEnums["json2object.Error"] = { __ename__:true,__constructs__:null
	,IncorrectType: ($_=function(variable,expected,pos) { return {_hx_index:0,variable:variable,expected:expected,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_._hx_name="IncorrectType",$_.__params__ = ["variable","expected","pos"],$_)
	,IncorrectEnumValue: ($_=function(value,expected,pos) { return {_hx_index:1,value:value,expected:expected,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_._hx_name="IncorrectEnumValue",$_.__params__ = ["value","expected","pos"],$_)
	,InvalidEnumConstructor: ($_=function(value,expected,pos) { return {_hx_index:2,value:value,expected:expected,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_._hx_name="InvalidEnumConstructor",$_.__params__ = ["value","expected","pos"],$_)
	,UninitializedVariable: ($_=function(variable,pos) { return {_hx_index:3,variable:variable,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_._hx_name="UninitializedVariable",$_.__params__ = ["variable","pos"],$_)
	,UnknownVariable: ($_=function(variable,pos) { return {_hx_index:4,variable:variable,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_._hx_name="UnknownVariable",$_.__params__ = ["variable","pos"],$_)
	,ParserError: ($_=function(message,pos) { return {_hx_index:5,message:message,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_._hx_name="ParserError",$_.__params__ = ["message","pos"],$_)
	,CustomFunctionException: ($_=function(e,pos) { return {_hx_index:6,e:e,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_._hx_name="CustomFunctionException",$_.__params__ = ["e","pos"],$_)
};
json2object_Error.__constructs__ = [json2object_Error.IncorrectType,json2object_Error.IncorrectEnumValue,json2object_Error.InvalidEnumConstructor,json2object_Error.UninitializedVariable,json2object_Error.UnknownVariable,json2object_Error.ParserError,json2object_Error.CustomFunctionException];
var json2object_InternalError = $hxEnums["json2object.InternalError"] = { __ename__:true,__constructs__:null
	,AbstractNoJsonRepresentation: ($_=function(name) { return {_hx_index:0,name:name,__enum__:"json2object.InternalError",toString:$estr}; },$_._hx_name="AbstractNoJsonRepresentation",$_.__params__ = ["name"],$_)
	,CannotGenerateSchema: ($_=function(name) { return {_hx_index:1,name:name,__enum__:"json2object.InternalError",toString:$estr}; },$_._hx_name="CannotGenerateSchema",$_.__params__ = ["name"],$_)
	,HandleExpr: {_hx_name:"HandleExpr",_hx_index:2,__enum__:"json2object.InternalError",toString:$estr}
	,ParsingThrow: {_hx_name:"ParsingThrow",_hx_index:3,__enum__:"json2object.InternalError",toString:$estr}
	,UnsupportedAbstractEnumType: ($_=function(name) { return {_hx_index:4,name:name,__enum__:"json2object.InternalError",toString:$estr}; },$_._hx_name="UnsupportedAbstractEnumType",$_.__params__ = ["name"],$_)
	,UnsupportedEnumAbstractValue: ($_=function(name) { return {_hx_index:5,name:name,__enum__:"json2object.InternalError",toString:$estr}; },$_._hx_name="UnsupportedEnumAbstractValue",$_.__params__ = ["name"],$_)
	,UnsupportedMapKeyType: ($_=function(name) { return {_hx_index:6,name:name,__enum__:"json2object.InternalError",toString:$estr}; },$_._hx_name="UnsupportedMapKeyType",$_.__params__ = ["name"],$_)
	,UnsupportedSchemaObjectType: ($_=function(name) { return {_hx_index:7,name:name,__enum__:"json2object.InternalError",toString:$estr}; },$_._hx_name="UnsupportedSchemaObjectType",$_.__params__ = ["name"],$_)
	,UnsupportedSchemaType: ($_=function(type) { return {_hx_index:8,type:type,__enum__:"json2object.InternalError",toString:$estr}; },$_._hx_name="UnsupportedSchemaType",$_.__params__ = ["type"],$_)
};
json2object_InternalError.__constructs__ = [json2object_InternalError.AbstractNoJsonRepresentation,json2object_InternalError.CannotGenerateSchema,json2object_InternalError.HandleExpr,json2object_InternalError.ParsingThrow,json2object_InternalError.UnsupportedAbstractEnumType,json2object_InternalError.UnsupportedEnumAbstractValue,json2object_InternalError.UnsupportedMapKeyType,json2object_InternalError.UnsupportedSchemaObjectType,json2object_InternalError.UnsupportedSchemaType];
var json2object_PositionUtils = function(content) {
	this.linesInfo = [];
	var s = 0;
	var e = 0;
	var i = 0;
	var lineCount = 0;
	while(i < content.length) switch(content.charAt(i)) {
	case "\n":
		e = i;
		this.linesInfo.push({ number : lineCount, start : s, end : e});
		++lineCount;
		++i;
		s = i;
		break;
	case "\r":
		e = i;
		if(content.charAt(i + 1) == "\n") {
			++e;
		}
		this.linesInfo.push({ number : lineCount, start : s, end : e});
		++lineCount;
		i = e + 1;
		s = i;
		break;
	default:
		++i;
	}
	this.linesInfo.push({ number : lineCount, start : s, end : i});
};
json2object_PositionUtils.__name__ = true;
json2object_PositionUtils.prototype = {
	convertPosition: function(position) {
		var file = position.file;
		var min = position.min;
		var max = position.max;
		var pos = { file : file, min : min + 1, max : max + 1, lines : []};
		var lastLine = this.linesInfo.length - 1;
		var bounds_min = 0;
		var bounds_max = lastLine;
		if(min > this.linesInfo[0].end) {
			while(bounds_max > bounds_min) {
				var i = (bounds_min + bounds_max) / 2 | 0;
				var line = this.linesInfo[i];
				if(line.start == min) {
					bounds_min = i;
					bounds_max = i;
				}
				if(line.end < min) {
					bounds_min = i + 1;
				}
				if(line.start > min || line.end >= min && line.start < min) {
					bounds_max = i;
				}
			}
		}
		var _g = bounds_min;
		var _g1 = this.linesInfo.length;
		while(_g < _g1) {
			var i = _g++;
			var line = this.linesInfo[i];
			if(line.start <= min && line.end >= max) {
				pos.lines.push({ number : line.number + 1, start : min - line.start + 1, end : max - line.start + 1});
				break;
			}
			if(line.start <= min && min <= line.end) {
				pos.lines.push({ number : line.number + 1, start : min - line.start + 1, end : line.end + 1});
			}
			if(line.start <= max && max <= line.end) {
				pos.lines.push({ number : line.number + 1, start : line.start + 1, end : max - line.start + 1});
			}
			if(line.start >= max || line.end >= max) {
				break;
			}
		}
		return pos;
	}
	,__class__: json2object_PositionUtils
};
var sys_FileSystem = function() { };
sys_FileSystem.__name__ = true;
sys_FileSystem.exists = function(path) {
	try {
		js_node_Fs.accessSync(path);
		return true;
	} catch( _g ) {
		return false;
	}
};
sys_FileSystem.isDirectory = function(path) {
	try {
		return js_node_Fs.statSync(path).isDirectory();
	} catch( _g ) {
		return false;
	}
};
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
if( String.fromCodePoint == null ) String.fromCodePoint = function(c) { return c < 0x10000 ? String.fromCharCode(c) : String.fromCharCode((c>>10)+0xD7C0)+String.fromCharCode((c&0x3FF)+0xDC00); }
Object.defineProperty(String.prototype,"__class__",{ value : String, enumerable : false, writable : true});
String.__name__ = true;
Array.__name__ = true;
var Int = { };
var Dynamic = { };
var Float = Number;
var Bool = Boolean;
var Class = { };
var Enum = { };
js_Boot.__toStr = ({ }).toString;
esb_core_config__$ConfigParser_ConfigPreProcessor.reg = new EReg("\\${(.*?)\\}","gm");
esb_core_config_sections_EsbConfig.reg = new EReg("\\{\\{(.*?)\\}\\}","gm");
esb_core_config_sections_PropertiesConfig.reg = new EReg("\\{(.*?)\\}","gm");
Test.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
var esb = $hx_exports["esb"];

//# sourceMappingURL=esb-config.js.map